MONGO_DB_NAME = "z_db"
MONGO_URI = "mongodb://localhost:27017/"
DEFAULT_COLLECTION_NAME = "z_collection"
PAGE_CONTENT_KEY = "name"
EMBEDDING_CONTEXT_LENGTH = 1536
EMBEDDING_ENCODING = "cl100k_base"
EMBEDDING_MODEL = "text-embedding-ada-002"
PROJECT_PATH = "/"