version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # location of your requirements/setup files
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
